Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "projeto01"
  config.vm.provision "shell", path: "script.sh"
  config.vm.provider "virtualbox" do |v|
  v.memory = "1024"
  v.cpus = "1"
  end
end

